#ifndef MH_MADHATTER_H
#define MH_MADHATTER_H

#include "mh_archive.h"
#include "mh_asset.h"
#include "mh_chapter_info.h"
#include "mh_dlz.h"
#include "mh_event_base_list.h"
#include "mh_event_descriptor_bank.h"
#include "mh_event_info_list.h"
#include "mh_file.h"
#include "mh_goal_info.h"
#include "mh_herbtea_event.h"
#include "mh_huffman.h"
#include "mh_layton_pack.h"
#include "mh_layton_pack2.h"
#include "mh_lz10.h"
#include "mh_anim.h"
#include "mh_datafiles.h"
#include "mh_font.h"
#include "mh_image.h"
#include "mh_place.h"
#include "mh_nazo.h"
#include "mh_nazo_list.h"
#include "mh_rle.h"
#include "mh_story_select_list.h"
#include "mh_storybook_photo.h"
#include "mh_stream.h"
#include "mh_submap_info.h"
#include "mh_time_definition.h"

#endif
